# DLT Config (PLEASE IGNORE THIS)
[runtime]
log_level="INFO"  # the system log level of dlt
# use the dlthub_telemetry setting to enable/disable anonymous usage data reporting, see https://dlthub.com/docs/telemetry
dlthub_telemetry = false

# Any user level edits, start here
[extract.csv]
path = "data/"
batch_size = 10000
